#!/usr/bin/env bash
#
# Verify the delegated CLI for Microsoft 365 workloads declared in the handoff:
# Outlook, Calendar, SharePoint, and/or OneDrive.
#
# By default this reads only metadata/counts. --write-probe checks SharePoint and
# --drive-write-probe checks OneDrive; both remove their temporary file.
#
set -euo pipefail
umask 077

M365_BIN="${M365_BIN:-m365}"
HANDOFF_FILE=""
OUTPUT_FILE=""
WRITE_PROBE=false
DRIVE_WRITE_PROBE=false

usage() {
  cat <<'EOF'
Usage:
  verify-clim365-access.sh \
    --handoff ./aria-contoso-microsoft/aria-m365-integration-handoff.json

Inputs:
  --handoff PATH       Handoff generated by provision-clim365-app.sh.
  --output PATH        Verification JSON; defaults next to the handoff.
  --write-probe        Upload a test .txt to SharePoint and recycle it.
  --drive-write-probe  Upload a test .txt to the user's OneDrive and delete it.
  -h, --help            Show this help.

Required before running:
  m365 login --authType deviceCode --appId <APP_ID> --tenant <TENANT_ID>

The login must be completed as the handoff's delegated integration user.

Default verification does not return subjects, event names, or filenames. It
keeps only technical counts and IDs. Write probes are optional and reversible.
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --handoff)
      [[ $# -ge 2 ]] || die "--handoff requires a value"
      HANDOFF_FILE="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || die "--output requires a value"
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --write-probe)
      WRITE_PROBE=true
      shift
      ;;
    --drive-write-probe)
      DRIVE_WRITE_PROBE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

[[ -n "$HANDOFF_FILE" ]] || die "--handoff is required"
[[ -f "$HANDOFF_FILE" ]] || die "handoff does not exist: $HANDOFF_FILE"
need_cmd "$M365_BIN"
need_cmd jq

jq -e '
  .schemaVersion == 3
  and (
    .integration == "aria-clim365-integration"
    or .integration == "aria-clim365-worker"
  )
  and (.tenantId | length > 0)
  and (.appId | length > 0)
  and (.delegatedIdentity.userPrincipalName | length > 0)
  and (.workloads | type == "object")
  and ((.workloads.outlook != true) or (
    (.permissions.microsoftGraph.delegated | index("Mail.ReadWrite") != null)
    and (.permissions.microsoftGraph.delegated | index("Mail.Send") != null)
  ))
  and ((.workloads.calendar != true) or (
    .permissions.microsoftGraph.delegated | index("Calendars.ReadWrite") != null
  ))
  and ((.workloads.drive != true) or (
    .permissions.microsoftGraph.delegated | index("Files.ReadWrite") != null
  ))
  and ((.workloads.sharePoint != true) or (
    (.sharePoint.siteUrl | length > 0)
    and (.sharePoint.defaultFolderUrl | length > 0)
    and (.sharePoint.graphSiteLookupUrl | length > 0)
    and (.permissions.microsoftGraph.delegated | index("Sites.ReadWrite.All") != null)
    and (.permissions.sharePointOnline.delegated | index("AllSites.Write") != null)
  ))
' "$HANDOFF_FILE" >/dev/null || die "handoff does not match the Microsoft 365 v3 contract"

TENANT_ID="$(jq -r '.tenantId' "$HANDOFF_FILE")"
APP_ID="$(jq -r '.appId' "$HANDOFF_FILE")"
INTEGRATION_USER_UPN="$(jq -r '.delegatedIdentity.userPrincipalName' "$HANDOFF_FILE")"
OUTLOOK_ENABLED="$(jq -r '.workloads.outlook == true' "$HANDOFF_FILE")"
CALENDAR_ENABLED="$(jq -r '.workloads.calendar == true' "$HANDOFF_FILE")"
SHAREPOINT_ENABLED="$(jq -r '.workloads.sharePoint == true' "$HANDOFF_FILE")"
DRIVE_ENABLED="$(jq -r '.workloads.drive == true' "$HANDOFF_FILE")"
SITE_URL="$(jq -r '.sharePoint.siteUrl // empty' "$HANDOFF_FILE")"
FOLDER_URL="$(jq -r '.sharePoint.defaultFolderUrl // empty' "$HANDOFF_FILE")"
GRAPH_SITE_LOOKUP_URL="$(jq -r '.sharePoint.graphSiteLookupUrl // empty' "$HANDOFF_FILE")"
EXPECTED_CLI_VERSION="$(jq -r '.cli.testedVersion' "$HANDOFF_FILE")"

if [[ -z "$OUTPUT_FILE" ]]; then
  OUTPUT_FILE="$(cd "$(dirname "$HANDOFF_FILE")" && pwd)/aria-m365-access-verification.json"
fi
[[ ! -e "$OUTPUT_FILE" ]] ||
  die "$OUTPUT_FILE already exists; move it or specify another --output"
[[ "$WRITE_PROBE" == false || "$SHAREPOINT_ENABLED" == true ]] ||
  die "--write-probe requires a handoff with SharePoint enabled"
[[ "$DRIVE_WRITE_PROBE" == false || "$DRIVE_ENABLED" == true ]] ||
  die "--drive-write-probe requires a handoff with Drive enabled"

echo "==> Checking CLI for Microsoft 365 commands"
"$M365_BIN" status --help options >/dev/null
"$M365_BIN" request --help options >/dev/null
if [[ "$OUTLOOK_ENABLED" == true ]]; then
  "$M365_BIN" outlook message list --help options >/dev/null
fi
if [[ "$CALENDAR_ENABLED" == true ]]; then
  "$M365_BIN" outlook calendar list --help options >/dev/null
fi
if [[ "$SHAREPOINT_ENABLED" == true ]]; then
  "$M365_BIN" spo web get --help options >/dev/null
  "$M365_BIN" spo file list --help options >/dev/null
fi
if [[ "$WRITE_PROBE" == true ]]; then
  "$M365_BIN" spo file add --help options >/dev/null
  "$M365_BIN" spo file remove --help options >/dev/null
fi

CLI_VERSION_RAW="$("$M365_BIN" version --output text)"
CLI_VERSION="$(printf '%s' "$CLI_VERSION_RAW" | tr -d '\r' | tail -n 1 | tr -d '[:space:]')"
[[ "$CLI_VERSION" == "$EXPECTED_CLI_VERSION" ]] ||
  die "expected CLI $EXPECTED_CLI_VERSION but found $CLI_VERSION"

echo "==> Checking active connection, App ID, tenant, and user"
STATUS_JSON="$("$M365_BIN" status --output json)"
CONNECTED_APP_ID="$(jq -r '.appId // empty' <<<"$STATUS_JSON")"
CONNECTED_TENANT="$(jq -r '.appTenant // empty' <<<"$STATUS_JSON")"
CONNECTED_AS="$(jq -r '.connectedAs // empty' <<<"$STATUS_JSON")"
AUTH_TYPE="$(jq -r '.authType // empty' <<<"$STATUS_JSON")"
[[ "$(lower "$CONNECTED_APP_ID")" == "$(lower "$APP_ID")" ]] ||
  die "m365 is using App ID $CONNECTED_APP_ID, not $APP_ID"
[[ "$(lower "$CONNECTED_TENANT")" == "$(lower "$TENANT_ID")" ]] ||
  die "m365 is using tenant $CONNECTED_TENANT, not $TENANT_ID"
[[ "$(lower "$CONNECTED_AS")" == "$(lower "$INTEGRATION_USER_UPN")" ]] ||
  die "m365 is connected as $CONNECTED_AS, not $INTEGRATION_USER_UPN"
[[ "$(lower "$AUTH_TYPE")" == "devicecode" ]] ||
  die "expected authType DeviceCode but found $AUTH_TYPE"

MAIL_COUNT=null
if [[ "$OUTLOOK_ENABLED" == true ]]; then
  echo "==> Checking Outlook without exposing content"
  MAIL_PROBE_JSON="$(
    "$M365_BIN" request \
      --url 'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=1&$select=id' \
      --output json
  )"
  MAIL_COUNT="$(jq -r '(.value // []) | length' <<<"$MAIL_PROBE_JSON")"
  [[ "$MAIL_COUNT" =~ ^[01]$ ]] || die "Outlook returned an unexpected sample count: $MAIL_COUNT"
fi

CALENDAR_COUNT=null
if [[ "$CALENDAR_ENABLED" == true ]]; then
  echo "==> Checking Calendar without exposing events"
  CALENDAR_PROBE_JSON="$(
    "$M365_BIN" request \
      --url 'https://graph.microsoft.com/v1.0/me/calendars?$top=1&$select=id' \
      --output json
  )"
  CALENDAR_COUNT="$(jq -r '(.value // []) | length' <<<"$CALENDAR_PROBE_JSON")"
  [[ "$CALENDAR_COUNT" =~ ^[01]$ ]] ||
    die "Calendar returned an unexpected sample count: $CALENDAR_COUNT"
fi

GRAPH_SITE_ID=""
SHAREPOINT_WEB_ID=""
SHAREPOINT_FILE_COUNT=null
if [[ "$SHAREPOINT_ENABLED" == true ]]; then
  echo "==> Resolving Microsoft Graph Site ID"
  GRAPH_SITE_JSON="$("$M365_BIN" request --url "$GRAPH_SITE_LOOKUP_URL" --output json)"
  GRAPH_SITE_ID="$(jq -r '.id // empty' <<<"$GRAPH_SITE_JSON")"
  [[ -n "$GRAPH_SITE_ID" ]] || die "Graph did not return the Site ID for $SITE_URL"

  echo "==> Checking SharePoint site and folder"
  SHAREPOINT_WEB_JSON="$("$M365_BIN" spo web get --url "$SITE_URL" --output json)"
  SHAREPOINT_WEB_ID="$(jq -r '.Id // .id // empty' <<<"$SHAREPOINT_WEB_JSON")"
  [[ -n "$SHAREPOINT_WEB_ID" ]] || die "SharePoint did not return the Web ID for $SITE_URL"
  SHAREPOINT_FILE_COUNT="$(
    "$M365_BIN" spo file list \
      --webUrl "$SITE_URL" \
      --folderUrl "$FOLDER_URL" \
      --query 'length(@)' \
      --output text
  )"
  [[ "$SHAREPOINT_FILE_COUNT" =~ ^[0-9]+$ ]] ||
    die "SharePoint returned an unexpected file count: $SHAREPOINT_FILE_COUNT"
fi

WRITE_PROBE_FILE=""
WRITE_PROBE_RECYCLED=false
if [[ "$WRITE_PROBE" == true ]]; then
  echo "==> Checking SharePoint write access with a temporary file"
  WRITE_PROBE_FILE="aria-onboarding-write-probe-$(date -u +%Y%m%dT%H%M%SZ).txt"
  LOCAL_PROBE_FILE="$(mktemp)"
  trap 'rm -f "${LOCAL_PROBE_FILE:-}"' EXIT
  printf 'ARIA Microsoft 365 onboarding write probe\n' >"$LOCAL_PROBE_FILE"
  "$M365_BIN" spo file add \
    --webUrl "$SITE_URL" \
    --folder "$FOLDER_URL" \
    --path "$LOCAL_PROBE_FILE" \
    --fileName "$WRITE_PROBE_FILE" \
    --output none
  PROBE_REMOTE_URL="/${FOLDER_URL#/}/$WRITE_PROBE_FILE"
  "$M365_BIN" spo file remove \
    --webUrl "$SITE_URL" \
    --url "$PROBE_REMOTE_URL" \
    --recycle \
    --force \
    --output none
  WRITE_PROBE_RECYCLED=true
fi

DRIVE_FILE_COUNT=null
DRIVE_WRITE_PROBE_FILE=""
DRIVE_WRITE_PROBE_RECYCLED=false
if [[ "$DRIVE_ENABLED" == true ]]; then
  echo "==> Checking OneDrive without exposing content"
  DRIVE_PROBE_JSON="$(
    "$M365_BIN" request \
      --url 'https://graph.microsoft.com/v1.0/me/drive/root/children?$top=1&$select=id' \
      --output json
  )"
  DRIVE_FILE_COUNT="$(jq -r '(.value // []) | length' <<<"$DRIVE_PROBE_JSON")"
  [[ "$DRIVE_FILE_COUNT" =~ ^[01]$ ]] ||
    die "OneDrive returned an unexpected sample count: $DRIVE_FILE_COUNT"
fi

if [[ "$DRIVE_WRITE_PROBE" == true ]]; then
  echo "==> Checking OneDrive write access with a temporary file"
  DRIVE_WRITE_PROBE_FILE="aria-onboarding-drive-probe-$(date -u +%Y%m%dT%H%M%SZ).txt"
  DRIVE_UPLOAD_JSON="$(
    "$M365_BIN" request \
      --method put \
      --url "https://graph.microsoft.com/v1.0/me/drive/root:/${DRIVE_WRITE_PROBE_FILE}:/content" \
      --content-type text/plain \
      --body 'ARIA Microsoft 365 OneDrive onboarding write probe' \
      --output json
  )"
  DRIVE_ITEM_ID="$(jq -r '.id // empty' <<<"$DRIVE_UPLOAD_JSON")"
  [[ -n "$DRIVE_ITEM_ID" ]] || die "OneDrive did not return the temporary file ID"
  "$M365_BIN" request \
    --method delete \
    --url "https://graph.microsoft.com/v1.0/me/drive/items/${DRIVE_ITEM_ID}" \
    --output none
  DRIVE_WRITE_PROBE_RECYCLED=true
fi

GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
jq -n \
  --arg generatedAt "$GENERATED_AT" \
  --arg tenantId "$TENANT_ID" \
  --arg appId "$APP_ID" \
  --arg connectedAs "$CONNECTED_AS" \
  --arg authType "$AUTH_TYPE" \
  --arg cliVersion "$CLI_VERSION" \
  --arg siteUrl "$SITE_URL" \
  --arg graphSiteId "$GRAPH_SITE_ID" \
  --arg sharePointWebId "$SHAREPOINT_WEB_ID" \
  --arg folderUrl "$FOLDER_URL" \
  --arg writeProbeFile "$WRITE_PROBE_FILE" \
  --arg driveWriteProbeFile "$DRIVE_WRITE_PROBE_FILE" \
  --argjson outlookEnabled "$OUTLOOK_ENABLED" \
  --argjson calendarEnabled "$CALENDAR_ENABLED" \
  --argjson sharePointEnabled "$SHAREPOINT_ENABLED" \
  --argjson driveEnabled "$DRIVE_ENABLED" \
  --argjson mailCount "$MAIL_COUNT" \
  --argjson calendarCount "$CALENDAR_COUNT" \
  --argjson sharePointFileCount "$SHAREPOINT_FILE_COUNT" \
  --argjson driveFileCount "$DRIVE_FILE_COUNT" \
  --argjson writeProbeRequested "$WRITE_PROBE" \
  --argjson writeProbeRecycled "$WRITE_PROBE_RECYCLED" \
  --argjson driveWriteProbeRequested "$DRIVE_WRITE_PROBE" \
  --argjson driveWriteProbeRecycled "$DRIVE_WRITE_PROBE_RECYCLED" \
  '{
    schemaVersion: 2,
    integration: "aria-clim365-access-verification",
    generatedAt: $generatedAt,
    tenantId: $tenantId,
    appId: $appId,
    connectedAs: $connectedAs,
    authType: $authType,
    cliVersion: $cliVersion,
    workloads: {
      outlook: $outlookEnabled,
      calendar: $calendarEnabled,
      sharePoint: $sharePointEnabled,
      drive: $driveEnabled
    },
    outlook: (if $outlookEnabled then {
      inboxReadable: true,
      sampleCountObserved: $mailCount
    } else null end),
    calendar: (if $calendarEnabled then {
      readable: true,
      sampleCountObserved: $calendarCount
    } else null end),
    sharePoint: (if $sharePointEnabled then {
      siteUrl: $siteUrl,
      graphSiteId: $graphSiteId,
      sharePointWebId: $sharePointWebId,
      defaultFolderUrl: $folderUrl,
      folderReadable: true,
      fileCountObserved: $sharePointFileCount,
      writeProbeRequested: $writeProbeRequested,
      writeProbeFile: (if $writeProbeFile == "" then null else $writeProbeFile end),
      writeProbeRecycled: $writeProbeRecycled
    } else null end),
    drive: (if $driveEnabled then {
      rootReadable: true,
      sampleCountObserved: $driveFileCount,
      writeProbeRequested: $driveWriteProbeRequested,
      writeProbeFile: (if $driveWriteProbeFile == "" then null else $driveWriteProbeFile end),
      writeProbeRecycled: $driveWriteProbeRecycled
    } else null end)
  }' >"$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"

echo "==> clim365 verification complete"
echo "    Controlled evidence: $OUTPUT_FILE"
echo "    Resolved Graph Site ID: $GRAPH_SITE_ID"
